baseURL = "http://hpmor.ru/"
languageCode = "ru-ru"
title = "Гарри Поттер и методы рационального мышления"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-32872324-1"
enableRobotsTXT = true

# run to allow robots.txt env HUGO_ENV="production" hugo

[[menu.main]]
    name = "Скачать: EPUB,"
    weight = -70
    identifier = "Скачать EPUB"
    url = "/files/hpmor_ru.epub"
    
[[menu.main]]
    name = "HTML,"
    weight = -60
    identifier = "HTML,"
    url = "/files/hpmor_ru.html"

[[menu.main]]
    name = "MOBI,"
    weight = -50
    identifier = "Скачать MOBI"
    url = "/files/hpmor_ru.mobi"
    
[[menu.main]]
    name = "FB2,"
    weight = -40
    identifier = "Скачать FB2"
    url = "/files/hpmor_ru.fb2.zip"
    
[[menu.main]]
    name = "ODPS"
    weight = -30
    identifier = "Каталог ODPS со всеми файлами книг"
    url = "/files/opds2.xml"
    
[[menu.main]]
    name = "Форум"
    weight = -100
    identifier = "Форум"
    url = "https://lesswrong.ru/forum/index.php?board=3.0"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "img/favicon.ico"
  description = "Элиезер Юдковский (Less Wrong)"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black-60"
  featured_image = "/img/hpmorlogo.svg"
  body_classes = "helvetica bg-white"
  # recent_posts_number = 2

